// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConfigPath() {
  return window['go']['main']['App']['ConfigPath']();
}

export function DeleteContent(arg1, arg2) {
  return window['go']['main']['App']['DeleteContent'](arg1, arg2);
}

export function FetchMetadata(arg1) {
  return window['go']['main']['App']['FetchMetadata'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContent(arg1) {
  return window['go']['main']['App']['GetContent'](arg1);
}

export function GetThumbnailDataURL(arg1) {
  return window['go']['main']['App']['GetThumbnailDataURL'](arg1);
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function InstallDependency(arg1) {
  return window['go']['main']['App']['InstallDependency'](arg1);
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function ListContent(arg1) {
  return window['go']['main']['App']['ListContent'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenInFolder(arg1) {
  return window['go']['main']['App']['OpenInFolder'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function PickFile(arg1, arg2) {
  return window['go']['main']['App']['PickFile'](arg1, arg2);
}

export function ResolveBinaries() {
  return window['go']['main']['App']['ResolveBinaries']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function VendorDir() {
  return window['go']['main']['App']['VendorDir']();
}
