// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {ytdlp} from '../models';
import {config} from '../models';
import {db} from '../models';
import {binaries} from '../models';
import {download} from '../models';

export function CancelDownload(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<updater.Info>;

export function ConfigPath():Promise<string>;

export function DeleteContent(arg1:number,arg2:boolean):Promise<void>;

export function FetchMetadata(arg1:string):Promise<ytdlp.Preview>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetContent(arg1:number):Promise<db.Content>;

export function GetThumbnailDataURL(arg1:number):Promise<string>;

export function GetUpdateStatus():Promise<updater.Info>;

export function InstallDependency(arg1:string):Promise<string>;

export function IsFirstRun():Promise<boolean>;

export function ListContent(arg1:db.ListOptions):Promise<db.ListResult>;

export function OpenFile(arg1:number):Promise<void>;

export function OpenInFolder(arg1:number):Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function PickFile(arg1:string,arg2:string):Promise<string>;

export function ResolveBinaries():Promise<Array<binaries.BinaryStatus>>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartDownload(arg1:download.DownloadRequest):Promise<string>;

export function VendorDir():Promise<string>;
